#name = "Laptop"

requirements = [
	{ name = "USB-C Power", priority = 10 },
	{ name = "USB-C Thunderbolt Dock", priority = 20 },
	{ name = "Libre Firmware", priority = 30 },
	{ name = "Screen DPI >= 96", priority = 40 },
	{ name = "Screen Size >= 13\"", priority = 50 },
	{ name = "External Display Resolution >= 4K", priority = 60 },
	{ name = "coreboot", priority = 70 },
	{ name = "WiFi 802.11ac", priority = 80 },
	{ name = "Bluetooth 5.0", priority = 90 },
	{ name = "Killswitch: Camera/Mic", priority = 100 },
	{ name = "Killswitch: Wireless", priority = 110 },
	{ name = "Libre Hardware", priority = 120 },
	{ name = "Aspect Ratio = 16:9", priority = 130 },
	{ name = "Screen Resolution >= 4K", priority = 140 },
	{ name = "Screen Resolution >= 8K" },
	{ name = "Screen Size >= 15\"" },
	{ name = "Touchscreen" },
]

items = [
	{ name = "Dell XPS 13", evaluations = [
		{ name = "USB-C Power", score = 1.0, comment = "" },
		{ name = "USB-C Thunderbolt Dock", score = 1.0, comment = "" },
		{ name = "Libre Firmware", score = -inf, comment = "" },
		{ name = "Screen DPI >= 96", score = 1.0, comment = "" },
		{ name = "Screen Size >= 13\"", score = -inf, comment = "" },
		{ name = "External Display Resolution >= 4K", score = 1.0, comment = "" },
		{ name = "coreboot", score = -inf, comment = "" },
		{ name = "WiFi 802.11ac", score = 1.0, comment = "" },
		{ name = "Bluetooth 5.0", score = -inf, comment = "" },
		{ name = "Killswitch: Camera/Mic", score = -inf, comment = "" },
		{ name = "Killswitch: Wireless", score = -inf, comment = "" },
		{ name = "Libre Hardware", score = -inf, comment = "" },
		{ name = "Aspect Ratio = 16:9", score = -inf, comment = "" },
		{ name = "Screen Resolution >= 4K", score = 1.0, comment = "Native resolution is 3840×2160." },
		{ name = "Screen Resolution >= 8K", score = -inf, comment = "" },
		{ name = "Screen Size >= 15\"", score = -inf, comment = "" },
		{ name = "Touchscreen", score = 1.0, comment = "" },
	]},
	{ name = "Librem 14", evaluations = [
		{ name = "USB-C Power", score = 1.0, comment = "" },
		{ name = "USB-C Thunderbolt Dock", score = 1.0, comment = "" },
		{ name = "Libre Firmware", score = 1.0, comment = "" },
		{ name = "Screen DPI >= 96", score = -inf, comment = "" },
		{ name = "Screen Size >= 13\"", score = 1.0, comment = "" },
		{ name = "External Display Resolution >= 4K", score = 1.0, comment = "" },
		{ name = "coreboot", score = 1.0, comment = "" },
		{ name = "WiFi 802.11ac", score = -inf, comment = "" },
		{ name = "Bluetooth 5.0", score = -inf, comment = "" },
		{ name = "Killswitch: Camera/Mic", score = 1.0, comment = "" },
		{ name = "Killswitch: Wireless", score = 1.0, comment = "" },
		{ name = "Libre Hardware", score = 0.5, comment = "" },
		{ name = "Aspect Ratio = 16:9", score = -inf, comment = "" },
		{ name = "Screen Resolution >= 4K", score = -inf, comment = "" },
		{ name = "Screen Resolution >= 8K", score = -inf, comment = "" },
		{ name = "Screen Size >= 15\"", score = -inf, comment = "" },
		{ name = "Touchscreen", score = 0.0, comment = "" },
	]},
	{ name = "Thinkpad X1 Carbon", evaluations = [
		{ name = "USB-C Power", score = 1.0, comment = "" },
		{ name = "USB-C Thunderbolt Dock", score = 1.0, comment = "" },
		{ name = "Libre Firmware", score = -inf, comment = "" },
		{ name = "Screen DPI >= 96", score = 1.0, comment = "" },
		{ name = "Screen Size >= 13\"", score = -inf, comment = "" },
		{ name = "External Display Resolution >= 4K", score = 1.0, comment = "" },
		{ name = "coreboot", score = -inf, comment = "" },
		{ name = "WiFi 802.11ac", score = -inf, comment = "" },
		{ name = "Bluetooth 5.0", score = -inf, comment = "" },
		{ name = "Killswitch: Camera/Mic", score = 0.3, comment = "Physical slide cover for camera." },
		{ name = "Killswitch: Wireless", score = -inf, comment = "" },
		{ name = "Libre Hardware", score = -inf, comment = "" },
		{ name = "Aspect Ratio = 16:9", score = -inf, comment = "" },
		{ name = "Screen Resolution >= 4K", score = -inf, comment = "" },
		{ name = "Screen Resolution >= 8K", score = -inf, comment = "" },
		{ name = "Screen Size >= 15\"", score = -inf, comment = "" },
		{ name = "Touchscreen", score = 0.0, comment = "" },
	]},
]
