requirements = [
	{ priority = 10, name = "Transport: LoRa Radio", force = false },
	{ priority = 20, name = "Operating System: Android", force = false },
	{ priority = 20, name = "Operating System: iOS", force = false },
	{ priority = 20, name = "Transport: Bluetooth LE", force = false },
	{ priority = 30, name = "Bridged Transport", force = false },
	{ priority = 30, name = "Operating System: Linux", force = false },
	{ priority = 30, name = "Transport: Internet", force = false },
	{ priority = 40, name = "Transport: Sneakernet", force = false },
	{ priority = 50, name = "Content Publishing", force = false },
	{ priority = 50, name = "E2EE Private Messages", force = false },
]

items = [
	{ name = "Briar", evaluations = [
		{ name = "Transport: LoRa Radio", score = -inf, comment = "" },
		{ name = "Operating System: Android", score = 1.0, comment = "" },
		{ name = "Operating System: iOS", score = 0.0, comment = "" },
		{ name = "Transport: Bluetooth LE", score = -inf, comment = "" },
		{ name = "Bridged Transport", score = -inf, comment = "" },
		{ name = "Operating System: Linux", score = -inf, comment = "" },
		{ name = "Transport: Internet", score = 1.0, comment = "" },
		{ name = "Transport: Sneakernet", score = -inf, comment = "" },
		{ name = "Content Publishing", score = -inf, comment = "" },
		{ name = "E2EE Private Messages", score = -inf, comment = "" },
	]},
	{ name = "MeshCore", evaluations = [
		{ name = "Transport: LoRa Radio", score = 1.0, comment = "" },
		{ name = "Operating System: Android", score = 1.0, comment = "" },
		{ name = "Operating System: iOS", score = 1.0, comment = "" },
		{ name = "Transport: Bluetooth LE", score = -inf, comment = "" },
		{ name = "Bridged Transport", score = -inf, comment = "" },
		{ name = "Operating System: Linux", score = -inf, comment = "" },
		{ name = "Transport: Internet", score = -inf, comment = "" },
		{ name = "Transport: Sneakernet", score = -inf, comment = "" },
		{ name = "Content Publishing", score = -inf, comment = "" },
		{ name = "E2EE Private Messages", score = -inf, comment = "" },
	]},
	{ name = "Meshtastic", evaluations = [
		{ name = "Transport: LoRa Radio", score = 1.0, comment = "" },
		{ name = "Operating System: Android", score = 1.0, comment = "" },
		{ name = "Operating System: iOS", score = 1.0, comment = "" },
		{ name = "Transport: Bluetooth LE", score = -inf, comment = "" },
		{ name = "Bridged Transport", score = 0.3, comment = "uncommon" },
		{ name = "Operating System: Linux", score = 1.0, comment = "" },
		{ name = "Transport: Internet", score = 0.3, comment = "uncommon" },
		{ name = "Transport: Sneakernet", score = -inf, comment = "" },
		{ name = "Content Publishing", score = 0.0, comment = "" },
		{ name = "E2EE Private Messages", score = -inf, comment = "" },
	]},
	{ name = "Sideband (Reticulum)", evaluations = [
		{ name = "Transport: LoRa Radio", score = 1.0, comment = "" },
		{ name = "Operating System: Android", score = 1.0, comment = "" },
		{ name = "Operating System: iOS", score = -inf, comment = "" },
		{ name = "Transport: Bluetooth LE", score = 0.3, comment = "external module" },
		{ name = "Bridged Transport", score = -inf, comment = "" },
		{ name = "Operating System: Linux", score = 1.0, comment = "" },
		{ name = "Transport: Internet", score = 1.0, comment = "" },
		{ name = "Transport: Sneakernet", score = 1.0, comment = "QR import/export" },
		{ name = "Content Publishing", score = -inf, comment = "" },
		{ name = "E2EE Private Messages", score = -inf, comment = "" },
	]},
	{ name = "bitchat", evaluations = [
		{ name = "Transport: LoRa Radio", score = 0.0, comment = "" },
		{ name = "Operating System: Android", score = 1.0, comment = "" },
		{ name = "Operating System: iOS", score = 1.0, comment = "" },
		{ name = "Transport: Bluetooth LE", score = 1.0, comment = "" },
		{ name = "Bridged Transport", score = 1.0, comment = "direct messages" },
		{ name = "Operating System: Linux", score = -inf, comment = "" },
		{ name = "Transport: Internet", score = 1.0, comment = "via nostr" },
		{ name = "Transport: Sneakernet", score = -inf, comment = "" },
		{ name = "Content Publishing", score = 0.0, comment = "" },
		{ name = "E2EE Private Messages", score = -inf, comment = "" },
	]},
]
