#name = "Mobile Home"

requirements = [
	{ priority = 10, name = "Four Wheel Drive", force = true },
	{ priority = 20, name = "Composting Toilet", force = false },
	{ priority = 20, name = "Solar Acquisition >= 250W", force = false },
	{ priority = 30, name = "RV Hookup: Electric", force = false },
	{ priority = 40, name = "Battery Capacity >= 10,000W", force = false },
	{ priority = 40, name = "Indoor Shower", force = false },
	{ priority = 40, name = "Refrigerator: 12v/24v", force = false },
	{ priority = 50, name = "Radiative Heating", force = false },
	{ priority = 60, name = "Cooktop: Electric", force = false },
	{ priority = 80, name = "Stealth Appearance", force = false },
	{ priority = 90, name = "Air Conditioning: Battery", force = false },
	{ priority = 90, name = "Air Conditioning: RV Hookup", force = false },
	{ priority = 90, name = "Black Water Capacity >= 10L", force = false },
	{ priority = 90, name = "Cooktop: Propane", force = false },
	{ priority = 90, name = "Legal Passengers >= 4", force = false },
	{ priority = 90, name = "Lofted Bed", force = false },
	{ priority = 90, name = "Refrigerator: 110v", force = false },
	{ priority = 90, name = "Refrigerator: Propane", force = false },
]

items = [
	{ name = "Earthship ESV-X", evaluations = [
		{ name = "Four Wheel Drive", score = 1.0, comment = "" },
		{ name = "Composting Toilet", score = 1.0, comment = "Separett" },
		{ name = "Solar Acquisition >= 250W", score = 1.0, comment = "420W Zamp Solar" },
		{ name = "RV Hookup: Electric", score = 1.0, comment = "" },
		{ name = "Battery Capacity >= 10,000W", score = 1.0, comment = "10,000W" },
		{ name = "Indoor Shower", score = 0.3, comment = "outdoor" },
		{ name = "Refrigerator: 12v/24v", score = -inf, comment = "" },
		{ name = "Radiative Heating", score = -inf, comment = "" },
		{ name = "Cooktop: Electric", score = -inf, comment = "" },
		{ name = "Stealth Appearance", score = -inf, comment = "" },
		{ name = "Air Conditioning: Battery", score = -inf, comment = "" },
		{ name = "Air Conditioning: RV Hookup", score = -inf, comment = "" },
		{ name = "Black Water Capacity >= 10L", score = -inf, comment = "" },
		{ name = "Cooktop: Propane", score = -inf, comment = "" },
		{ name = "Legal Passengers >= 4", score = -inf, comment = "" },
		{ name = "Lofted Bed", score = -inf, comment = "" },
		{ name = "Refrigerator: 110v", score = -inf, comment = "" },
		{ name = "Refrigerator: Propane", score = -inf, comment = "" },
	]},
	{ name = "Storyteller Beast Mode", evaluations = [
		{ name = "Four Wheel Drive", score = 1.0, comment = "" },
		{ name = "Composting Toilet", score = 0.3, comment = "toilet genie" },
		{ name = "Solar Acquisition >= 250W", score = 1.0, comment = "" },
		{ name = "RV Hookup: Electric", score = -inf, comment = "" },
		{ name = "Battery Capacity >= 10,000W", score = -inf, comment = "" },
		{ name = "Indoor Shower", score = 0.9, comment = "halo system" },
		{ name = "Refrigerator: 12v/24v", score = -inf, comment = "" },
		{ name = "Radiative Heating", score = -inf, comment = "" },
		{ name = "Cooktop: Electric", score = -inf, comment = "" },
		{ name = "Stealth Appearance", score = -inf, comment = "" },
		{ name = "Air Conditioning: Battery", score = -inf, comment = "" },
		{ name = "Air Conditioning: RV Hookup", score = -inf, comment = "" },
		{ name = "Black Water Capacity >= 10L", score = -inf, comment = "" },
		{ name = "Cooktop: Propane", score = -inf, comment = "" },
		{ name = "Legal Passengers >= 4", score = -inf, comment = "" },
		{ name = "Lofted Bed", score = -inf, comment = "" },
		{ name = "Refrigerator: 110v", score = -inf, comment = "" },
		{ name = "Refrigerator: Propane", score = -inf, comment = "" },
	]},
	{ name = "Winnebago Revel", evaluations = [
		{ name = "Four Wheel Drive", score = 1.0, comment = "" },
		{ name = "Composting Toilet", score = 0.0, comment = "casette toilet" },
		{ name = "Solar Acquisition >= 250W", score = -inf, comment = "" },
		{ name = "RV Hookup: Electric", score = -inf, comment = "" },
		{ name = "Battery Capacity >= 10,000W", score = -inf, comment = "" },
		{ name = "Indoor Shower", score = 1.0, comment = "wet bath" },
		{ name = "Refrigerator: 12v/24v", score = -inf, comment = "" },
		{ name = "Radiative Heating", score = -inf, comment = "" },
		{ name = "Cooktop: Electric", score = -inf, comment = "" },
		{ name = "Stealth Appearance", score = -inf, comment = "" },
		{ name = "Air Conditioning: Battery", score = -inf, comment = "" },
		{ name = "Air Conditioning: RV Hookup", score = -inf, comment = "" },
		{ name = "Black Water Capacity >= 10L", score = -inf, comment = "" },
		{ name = "Cooktop: Propane", score = -inf, comment = "" },
		{ name = "Legal Passengers >= 4", score = -inf, comment = "" },
		{ name = "Lofted Bed", score = -inf, comment = "" },
		{ name = "Refrigerator: 110v", score = -inf, comment = "" },
		{ name = "Refrigerator: Propane", score = -inf, comment = "" },
	]},
]
